### ISSUE TITLE
update 0.8.3 error

### ISSUE THREAD

**Issue by mostechlee** [dutu/poloLender#66]
mostech@zzlzzl:~/www/poloLender$ node server.js 
module.js:471
    throw err;
    ^

Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mostech/www/poloLender/server.js:3:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Running 0.8.2 ok but 0.8.3 error above.

**Comment by dutu** [comment]
You'd need to run `npm update`.
Please see [Updating the application](https://github.com/dutu/poloLender#updating-the-application) in the README file.
