### ISSUE TITLE
SyntaxError after update

### ISSUE THREAD

**Issue by demeo** [dutu/poloLender#78]
After last update I cannot start poloLender I do have this error:

[demeo@s3]:<~/.secret/poloLender>$ node server.js
/usr/home/polo/poloLender/server/core/logger.js:4
let customLogLevels = _.clone(winston.config.syslog.levels);
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> 
 (/usr/home/polo/poloLender/server/core/srv.js:16:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by dutu** [comment]
Please update your node.js version
