### ISSUE TITLE
Current pull with new Telegram enhancements breaks program.

### ISSUE THREAD

**Issue by abclution** [dutu/poloLender#80]
This is after updating my previous install. 

module.js:471
    throw err;
    ^

Error: Cannot find module 'node-telegram-bot-api'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/asdfsdf/Desktop/mybots/testing/poloLender/server/workers/poloLender/poloLender.js:13:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by abclution** [comment]
Just did a clean git clone and now getting this.. 

module.js:471
    throw err;
    ^

Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/asdfsad/Desktop/mybots/testing/asdfasdf/poloLender/server.js:3:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by dutu** [comment]
Did you run `npm update`? 
See the instruction to update the application in the readme file

**Comment by abclution** [comment]
Thank you. I missed that step, not familiar with npm stuff. 👍 

Fixed.
