### ISSUE TITLE
Error while starting bot. 

### ISSUE THREAD

**Issue by demeo** [dutu/poloLender#99]
[eve@s3]:<~/qwe/poloLender>$ node7 server.js 
report: Join poloLender discussion/support group on telegram: https://t.me/cryptozone
info: Using POLOLENDER_REPORTINTERVAL=30
info: Using POLOLENDER_STARTTIME=Tue Jul 11 2017 03:00:09 GMT+0200
info: Using POLOLENDER_STARTBALANCE={"BTC":"0.61574197","DOGE":"205670.10309281"}
info: Using POLOLENDER_LENDMAX={"BTC":"5","STR":"100000","DOGE":"280330"}
info: Using POLOLENDER_MINRATE={"BTC":"0","STR":"0","DOGE":"0","XRP":"0","LTC":"0","BTS":"0"}
info: Using POLOLENDER_STARTTIME=2017-07-11T01:00:09Z
notice: Bot reports will NOT be sent via telegram (token and/or userId not configured)
info: Listening on Port 10000
/usr/home/demeo/qwe/poloLender/node_modules/big.js/big.js:317
        throw err;
        ^

BigError: NaN
    at throwErr (/usr/home/demeo/qwe/poloLender/node_modules/big.js/big.js:314:19)
    at parse (/usr/home/demeo/qwe/poloLender/node_modules/big.js/big.js:184:13)
    at Big (/usr/home/demeo/qwe/poloLender/node_modules/big.js/big.js:90:17)
    at currencies.forEach.currency (/usr/home/demeo/qwe/poloLender/server/workers/poloLender/poloLender.js:803:17)
    at Array.forEach (native)
    at emitPerformanceUpdate (/usr/home/demeo/qwe/poloLender/server/workers/poloLender/poloLender.js:798:16)
    at Namespace.onBrowserConnection (/usr/home/demeo/qwe/poloLender/server/workers/poloLender/poloLender.js:873:5)
    at emitOne (events.js:96:13)
    at Namespace.emit (events.js:191:7)
    at Namespace.emit (/usr/home/demeo/qwe/poloLender/node_modules/socket.io/lib/namespace.js:212:10)

**Comment by dutu** [comment]
It looks that this issue occurs just after the app starts, when the web browser is requesting data from the lending engine and the data has not been received yet from Poloniex. 
It will be fixed in the next version.

In the meantime, as workaround, make sure you only open the web browser after the application has started.

**Comment by dutu** [comment]
Fixed in version 1.0.0
